name: Say Hello and Comment on PR

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
      - name: Display a message in logs
        run: echo "Hello from GitHub Actions!"

      - name: Add a comment to the PR
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.issues.createComment({
              issue_number: context.payload.pull_request.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "Hello from GitHub Actions! Thanks for your contribution."
            })
